---
- name: Create inventory
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Add bastion host
    ansible.builtin.add_host:
      name: "{{ lookup('ansible.builtin.env', 'BASTION_HOST') }}"
      ansible_ssh_host: "{{ lookup('ansible.builtin.env', 'BASTION_HOST') }}"
      ansible_ssh_port: "{{ lookup('ansible.builtin.env', 'BASTION_PORT') }}"
      ansible_ssh_user: "{{ lookup('ansible.builtin.env', 'BASTION_USER') }}"
      ansible_ssh_pass: "{{ lookup('ansible.builtin.env', 'BASTION_PASSWORD') }}"
      ansible_become_password: "{{ lookup('ansible.builtin.env', 'BASTION_PASSWORD') }}"

- name: Setup bastion
  hosts: all:!localhost
  gather_facts: false
  vars:
    litellm_api_url: "{{ lookup('ansible.builtin.file', '/user_data/litellm_api_base_url') | default('') }}"
    litellm_api_key: "{{ lookup('ansible.builtin.file', '/user_data/litellm_virtual_key') | default('') }}"
    litellm_models: "{{ lookup('ansible.builtin.file', '/user_data/litellm_available_models_list') | default('') }}"
  tasks:
  - name: Wait for bastion to be reachable
    ansible.builtin.wait_for_connection:
      timeout: 300
      delay: 10

  - name: Write LiteMaaS env vars to .bashrc
    ansible.builtin.blockinfile:
      path: "/home/{{ lookup('ansible.builtin.env', 'BASTION_USER') }}/.bashrc"
      marker: "# {mark} LITEMAAS ENV VARS"
      block: |
        export LITELLM_API_URL="{{ litellm_api_url }}"
        export LITELLM_API_KEY="{{ litellm_api_key }}"
        export LITELLM_MODELS="{{ litellm_models }}"
    when: litellm_api_key | length > 0
